### ISSUE TITLE
Named parameter as a part of a segment

### ISSUE THREAD

**Issue by veelenga** [amberframework/amber-router#7]
First of all thanks for your work here. I started to upgrade one of my projects to the latest Amber and notice and a small difference in a routing. 

For a moment, the named parameter can [only match the segment](https://github.com/amberframework/amber-router/blob/master/src/amber/router/route_set.cr#L37) (starts with a semicolon in a segment).

I would like to define named parameter in a route which is only a part of a segment i.e.:

```
route_set.add "/get/users/=:uid", :users
```

Would you like to support it? If yes, I can prepare a PR for this.

**Comment by robacarp** [comment]
Interesting idea. My only fear is that changing the way an incoming url is split will add overhead to the matching routine and slow down the tree navigation. Currently incoming URLs are split by slash and the tree is navigated by full segments. My instinct is that you'd need to add another character to the split in order to make that work, but that's just off the top of my head.

What's the end goal here? I'm trying to think and I'm wondering if you're headed towards something like name value pairs in the URL? Eg. `/get/users/name=rob/job=software`

**Comment by veelenga** [comment]
I [use such a route](https://github.com/crystal-community/crystal-ann/blob/master/config/routes.cr#L30) in Crystal ANN, where `=` is an indicator for a shortened URL(i.e. https://crystal-ann.com/=dQwYE). It is inspired by elixirstatus (http://elixirstatus.com/=gLk4), which is written in Phoenix.

**Comment by robacarp** [comment]
Interesting. I'm not opposed to looking at a pull for code for this, but it's not impossible to get the URL scheme you're looking for with the current code. Elsewhere route "filters" have been proposed which would run after a set of routes is matched to try and eliminate multiple matches, and this could be implemented in terms of that.

Since this route tree chooses routes by insertion order, rearranging your routes to have the short url at the bottom and stripping the equal sign in the controller could get you by until this problem is solved. 

Edit: code sample not needed

**Comment by veelenga** [comment]
> Since this route tree chooses routes by insertion order, rearranging your routes to have the short url at the bottom and stripping the equal sign in the controller could get you by until this problem is solved.

I know. But that means I would need to have a custom logic for something the router should be responsible for. I will try to prepare a PR and if you wouldn't be satisfied with the implementation, will use this suggestion for backward compatibility reasons in crystal-ann. Thanks for the response.

**Comment by eliasjpr** [comment]
Not sure if the following comment would be useful but it seems that an easy win would be to have aliases to the way params are defined in the path. WDYT?

**Comment by robacarp** [comment]
@eliasjpr I’m not sure what you mean

**Comment by eliasjpr** [comment]
Sorry, I should have added context. 

Right now params are prefixed with a `:` what if an option can be set to redefined the param prefix, for example `prefix = '=:'`? be able to define one or multiple prefixes. I am not sure if this fixes @veelenga  needs.

**Comment by robacarp** [comment]
I don't think that would address the problem. The `:` delineates a parameter definition in the routes file, while the issue as requested is to have a parameter be able to start in the middle of a segment. I'd rather address this by providing a filter mechanism:

```crystal
route_set.add "/get/users/:uid", :users, match: -> (uid) { uid[0] == "=" }
```
(or something)

**Comment by veelenga** [comment]
Sorry, guys. I don't have time to finish this task. Closing it for now. Thanks to everyone for participation.

**Comment by Blacksmoke16** [comment]
FWIW, by supporting _only_ the `:` based style has some issues of its own.

1. There is no way to denote the end of placeholder, e.x. `:name.html` would be looking for `name.html`.
2. There is no way to have multiple placeholders in a single segment, e.x. `:name.:format`.

Thoughts on taking another look at #18?  This would at least open the door for allowing these shortcomings, i.e. `{name}.html` and `{name}.{format}`.  The parsing of each segment would need to be updated to iterate thru the chars to track the opening/closing of the delimiters, but I don't think it would be that hard.

**Comment by robacarp** [comment]
In Amber, the format thing [is handled elsewhere](https://github.com/amberframework/amber/blob/master/src/amber/router/router.cr#L63-L69), by essentially just adding more than one route to the tree. It's not my favorite solution but it works.

The logic around segmentizing urls in here is [pretty simple](https://github.com/amberframework/amber-router/blob/master/src/amber_router/route_set.cr#L216). Adding a period to the segment splitter seems fine to me, and it seems like the right thing to do. Easy win without much casualty -- might need some tweak to the [other code called amber router](https://github.com/amberframework/amber/blob/master/src/amber/router/router.cr) but it would likely simplify it rather than add complexity.

Where the algorithm slows down with partial "segment" matching is with request-time url parsing. Right now the route matcher can make a bunch of assumptions about an incoming url because we can segment the request by slashes and assign each segment to a position in the route tree. Switching to segmenting on character boundaries would functionally require a complete rethink of the algorithm, but adding a second segment split character would not. 

The url template formatting with `{}` is nice, but it leads to the same problem that character wise parsing leads to. For example this route template: `/user:{user_id}/` would generate urls which look like this: `/user:23/` which doesn't look bad at all. The request-time parser is where the problem lies. It will need to iterate each character in the string `/user:23/` (because what if it's `/usef:23/` or `/robacarp/` etc) and for each character decide where on the tree to match that. Worst case scenario is: `/user:23/non-existent-path` which results in at least 9 "placements" or "tree segment matches" before short circuiting at `n` at position 8. Relying on the / to both start and end the segments means the request time parser can evaluate the similar path `/user/23/non-existent-path` in 3 matches -- "user" can be compared wholly, without looking at the tree, 23 need not be compared at all, and "non-existent-path" falls off the end of the tree branch and fails to route.

So the logical boundaries for the algorthim have been constructed as:

- segments are between fixed single characters which are present in both the template and the request urls
- url variables encompass an entire segment

And this is done to ensure that when a request comes it takes very little time to parse. There are certainly other algorithms at our disposal, and even reference code if you're interested enough in Phoenix to take a look. The router as it currently stands would be likely a performance bottleneck if converted to a character tree instead of a segment tree.

Hopefully that explains why I haven't given any attention to other variable matching scenarios 🍌 😀
